version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 804298342443.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=804298342443.dkr.ecr.us-east-1.amazonaws.com/lambda-ffmpeg-processor
      - IMAGE_TAG=latest
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - imageDetail.json